export const ROUTES = {
    SPLASH: 'Splash',
    LOGIN: 'Login',
    REGISTER: 'Register',
    FORGOT_PASSWORD: 'ForgotPassword',
    WELCOME: 'Welcome',
    MAIN: 'Main',
    PROFILE: 'Profile',
    EDIT_PROFILE: 'EditProfile',
    PRIVACY_SECURITY: 'PrivacySecurity',
    CHANGE_PASSWORD: 'ChangePassword',
    PASSWORD_SUCCESS: 'PasswordSuccess',
    BLOCKED_USERS: 'BlockedUsersScreen',
    BARCODE_SCANNER: 'BarcodeScanner',
    SEARCH_BOOK: 'SearchBook',
    BOOKS_LIST: 'BooksList',
    BOOK_DETAILS: 'BooksDetails',
    SEARCH: 'Search',
    PUBLICATION: 'Publication',
    /** @see PublicationDetailsParams in screens/Publication/PublicationDetailsScreen.js */
    PUBLICATION_DETAILS: 'PublicationDetails',
    /** @see MyPublicationDetailsParams in screens/Profile/MyBooks/MyPublicationDetailsScreen.js */
    MY_PUBLICATION_DETAILS: 'MyPublicationDetails',
    STEP_ONE_OFFER: 'StepOneOffer',
    STEP_TWO_OFFER: 'StepTwoOffer',
    PUBLIC_PROFILE_SCREEN: 'PublicProfileScreen',
    FAVORITES: 'Favorites',
    REVIEWS: 'Reviews',
    LEVELS: 'Levels',
    CHAT_ROOM: 'ChatRoom',
    SELECT_SWAP_BOOK: 'SelectSwapBook',
    SELECT_SWAP_LOCATION: 'SelectSwapLocation',
    QR_DISPLAY: 'DisplayQrCode',
    QR_SCANNER: 'ScanQrCode',
    REVIEW_SWAPPER: 'Review',
    MY_BOOKS: 'MyBooks',
    NOTIFICATIONS: 'Notifications',
} as const;
