/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconLucideAlertTriangle: typeof import('~icons/lucide/alert-triangle').default
  const IconLucideBan: typeof import('~icons/lucide/ban').default
  const IconLucideBell: typeof import('~icons/lucide/bell').default
  const IconLucideBookOpen: typeof import('~icons/lucide/book-open').default
  const IconLucideBookmark: typeof import('~icons/lucide/bookmark').default
  const IconLucideCheckCircle2: typeof import('~icons/lucide/check-circle2').default
  const IconLucideChevronDown: typeof import('~icons/lucide/chevron-down').default
  const IconLucideChevronLeft: typeof import('~icons/lucide/chevron-left').default
  const IconLucideChevronRight: typeof import('~icons/lucide/chevron-right').default
  const IconLucideClipboardList: typeof import('~icons/lucide/clipboard-list').default
  const IconLucideClock: typeof import('~icons/lucide/clock').default
  const IconLucideDownload: typeof import('~icons/lucide/download').default
  const IconLucideExternalLink: typeof import('~icons/lucide/external-link').default
  const IconLucideEye: typeof import('~icons/lucide/eye').default
  const IconLucideFileText: typeof import('~icons/lucide/file-text').default
  const IconLucideFlag: typeof import('~icons/lucide/flag').default
  const IconLucideInfo: typeof import('~icons/lucide/info').default
  const IconLucideLayoutDashboard: typeof import('~icons/lucide/layout-dashboard').default
  const IconLucideMessageCircle: typeof import('~icons/lucide/message-circle').default
  const IconLucideMoreVertical: typeof import('~icons/lucide/more-vertical').default
  const IconLucideSearch: typeof import('~icons/lucide/search').default
  const IconLucideSettings: typeof import('~icons/lucide/settings').default
  const IconLucideUser: typeof import('~icons/lucide/user').default
  const IconLucideUserCircle2: typeof import('~icons/lucide/user-circle2').default
  const IconLucideUserX: typeof import('~icons/lucide/user-x').default
  const IconLucideUsers: typeof import('~icons/lucide/users').default
}
