/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconLucideBan: typeof import('~icons/lucide/ban').default
  const IconLucideBell: typeof import('~icons/lucide/bell').default
  const IconLucideBookOpen: typeof import('~icons/lucide/book-open').default
  const IconLucideChevronDown: typeof import('~icons/lucide/chevron-down').default
  const IconLucideChevronLeft: typeof import('~icons/lucide/chevron-left').default
  const IconLucideChevronRight: typeof import('~icons/lucide/chevron-right').default
  const IconLucideFileText: typeof import('~icons/lucide/file-text').default
  const IconLucideFlag: typeof import('~icons/lucide/flag').default
  const IconLucideLayoutDashboard: typeof import('~icons/lucide/layout-dashboard').default
  const IconLucideSearch: typeof import('~icons/lucide/search').default
  const IconLucideSettings: typeof import('~icons/lucide/settings').default
  const IconLucideUser: typeof import('~icons/lucide/user').default
  const IconLucideUserX: typeof import('~icons/lucide/user-x').default
  const IconLucideUsers: typeof import('~icons/lucide/users').default
}
