import { StyleSheet } from 'react-native';

import { Fonts } from '@readme/shared/src/constants/theme';
import { withOpacity } from '@readme/shared/src/utils/colorUtils';

export const buildPublicProfileStyles = (theme) => {
    return StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: theme.background,
        },
        centerAll: {
            justifyContent: 'center',
            alignItems: 'center'
        },
        topButtonsContainer: {
            position: 'absolute',
            top: 5,
            left: 0,
            right: 0,
            zIndex: 10,
            flexDirection: 'row',
            justifyContent: 'space-between',
            paddingHorizontal: 20,
            paddingTop: 10,
        },
        iconButton: {
            width: 44,
            height: 44,
            backgroundColor: theme.headerBackground,
            borderRadius: 12,
            justifyContent: 'center',
            alignItems: 'center',
            opacity: 0.9,
        },
        scrollContent: {
            paddingBottom: 60,
        },
        imageContainer: {
            height: 320, 
            backgroundColor: theme.coverPlaceholder || '#EACCA5',
            borderBottomLeftRadius: 32,
            borderBottomRightRadius: 32,
            overflow: 'hidden',
        },
        profileImage: {
            width: '100%',
            height: '100%',
        },
        placeholderBackground: {
            flex: 1,
            backgroundColor: '#D1BFAe', 
            justifyContent: 'center',
            alignItems: 'center',
        },
        infoContainer: {
            paddingHorizontal: 24,
            paddingTop: 24,
            paddingBottom: 16,
        },
        headerRow: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: 12,
        },
        nameWrapper: {
            flexDirection: 'row',
            alignItems: 'center',
            flex: 1,
            paddingRight: 16,
        },
        name: {
            fontSize: 28,
            fontFamily: Fonts.inter_bold || 'System',
            fontWeight: '800',
            color: theme.textDisplay,
            letterSpacing: -0.5,
        },
        badgeRow: {
            flexDirection: 'row',
            alignItems: 'center',
            marginBottom: 14,
        },
        badgeImage: {
            width: 50,
            height: 50,
            marginRight: 6,
        },
        badgeText: {
            fontSize: 16,
            fontFamily: Fonts.inter_semi || 'System',
            color: theme.subtext,
        },
        bio: {
            fontSize: 15,
            lineHeight: 22,
            fontFamily: Fonts.inter_regular || 'System',
            color: theme.subtext,
            marginBottom: 24,
        },
        statsCard: {
            flexDirection: 'row',
            backgroundColor: theme.cardBackground || '#F8F9FA',
            borderRadius: 20,
            paddingVertical: 16,
            paddingHorizontal: 24,
            alignItems: 'center',
            borderWidth: 1,
            borderColor: theme.borderLight || '#F0F0F0',
        },
        statItem: {
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
        },
        statIconContainer: {
            width: 45,
            height: 45,
            borderRadius: 14,
            backgroundColor: withOpacity( theme.primary, 0.085 ),
            justifyContent: 'center',
            alignItems: 'center',
            marginRight: 12,
        },
        statNumber: {
            fontFamily: Fonts.inter_bold || 'System',
            fontSize: 18,
            fontWeight: '700',
            color: theme.textItemTitle,
        },
        statLabel: {
            fontFamily: Fonts.inter_regular || 'System',
            fontSize: 14,
            color: theme.textAuthor,
            marginTop: 2,
        },
        statDivider: {
            width: 1,
            height: 36,
            backgroundColor: theme.borderLight || '#E5E5E5',
            marginHorizontal: 16,
        },
        followButton: {
            backgroundColor: theme.primary, 
            paddingVertical: 10,
            paddingHorizontal: 22,
            borderRadius: 100, 
            shadowColor: theme.primary,
            shadowOffset: { width: 0, height: 4 }, 
            shadowOpacity: 0.3,                 
            shadowRadius: 8,                    
            elevation: 4,                       
        },
        followButtonText: {
            color: '#FFFFFF',
            fontSize: 14,
            fontFamily: Fonts.inter_semi || 'System',
            fontWeight: '700',
        },
        followingButton: {
            backgroundColor: 'transparent', 
            borderColor: theme.borderLight || '#E5E5E5',
            borderWidth: 1.5,
            shadowOpacity: 0, 
            elevation: 0,
        },
        followingButtonText: {
            color: theme.textDisplay,
        },
        tabContainer: {
            flexDirection: 'row',
            paddingHorizontal: 24,
            marginTop: 8,
            borderBottomWidth: 1,
            borderBottomColor: theme.borderLight || '#F0F0F0',
        },
        tab: {
            paddingVertical: 12,
            marginRight: 32,
            position: 'relative',
        },
        tabText: {
            fontFamily: Fonts.inter_semi || 'System',
            fontWeight: '600',
            fontSize: 15,
            color: theme.textMuted,
        },
        activeTabText: {
            color: theme.textItemTitle,
        },
        activeIndicator: {
            position: 'absolute',
            bottom: -1,
            left: 0,
            right: 0,
            height: 3,
            backgroundColor: theme.primary,
            borderTopLeftRadius: 3,
            borderTopRightRadius: 3,
        },
        tabContentContainer: {
            paddingHorizontal: 20,
            paddingTop: 24,
        },
        gridContainer: {
            flexDirection: 'row',
            flexWrap: 'wrap',
            justifyContent: 'space-between',
        },
        publicationCard: {
            width: '47.5%',
            marginBottom: 20,
        },
        bookCoverPlaceholder: {
            width: '100%',
            aspectRatio: 3 / 4, 
            backgroundColor: theme.coverPlaceholder || '#F4F4F5',
            borderRadius: 16,
            alignItems: 'center',
            justifyContent: 'center',
            marginBottom: 10,
            overflow: 'hidden',
            borderWidth: 1,
            borderColor: 'rgba(0,0,0,0.03)',
        },
        bookCoverImage: {
            width: '100%',
            height: '100%',
        },
        bookInfo: {
            paddingHorizontal: 4,
        },
        bookTitle: {
            fontFamily: Fonts.inter_semi || 'System',
            fontWeight: '600',
            fontSize: 14,
            color: theme.textItemTitle || '#1C1C1E',
        },
        emptyStateContainer: {
            paddingTop: 48,
            paddingBottom: 48,
            alignItems: 'center',
            justifyContent: 'center',
        },
        emptyStateText: {
            fontFamily: Fonts.inter_regular || 'System',
            color: theme.textMuted || '#999999',
            fontSize: 15,
            marginTop: 16,
        },
        reviewsListContainer: {
            width: '100%',
            paddingBottom: 20,
        },
        reviewCard: {
            backgroundColor: theme.cardBackground || '#FFFFFF',
            padding: 16,
            borderRadius: 16,
            marginBottom: 16,
            borderWidth: 1,
            borderColor: theme.borderLight || '#F0F0F0',
        },
        reviewHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: 8,
        },
        reviewAuthor: {
            fontFamily: Fonts.inter_semi || 'System',
            fontWeight: '600',
            fontSize: 15,
            color: theme.textItemTitle || '#1C1C1E',
        },
        ratingContainer: {
            flexDirection: 'row',
            gap: 2,
        },
        reviewText: {
            fontFamily: Fonts.inter_regular || 'System',
            fontSize: 14,
            lineHeight: 20,
            color: theme.subtext || '#666666',
            marginBottom: 12,
        },
        reviewDate: {
            fontFamily: Fonts.inter_regular || 'System',
            fontSize: 12,
            color: theme.textMuted || '#999999',
            textAlign: 'right',
        },
    });
};
