export const WEB_ROUTES = {
    WELCOME: '/welcome',
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    BOOKS: '/books',
    PUBLICATIONS: '/profile/publications',
    BOOKS_SCAN: '/books/scan',
    EXPLORE: '/explore',
    CHAT: '/chat',
    PROFILE: '/profile',
    PROFILE_EDIT: '/profile/edit',
    PROFILE_CHANGE_PASSWORD: '/profile/change-password',
    PROFILE_SET_PASSWORD: '/profile/set-password',
    PROFILE_PRIVACY_SECURITY: '/profile/privacy-security',
    PROFILE_BLOCKED_USERS: '/profile/blocked-users',
    PROFILE_FOLLOWING: '/profile/following',
    PROFILE_FOLLOWERS: '/profile/followers',
    PROFILE_FOLLOW_REQUESTS: '/profile/follow-requests',
    PROFILE_FAVORITES: '/profile/favorites',
    PROFILE_MY_BOOKS: '/profile/my-books',
    PROFILE_LEVEL: '/profile/level',
    PUBLICATION_NEW: '/publications/new',
    OFFERS_NEW: '/offers/new',
    bookDetail: (bookId) => `/books/${bookId}`,
    publicationDetail: (pubId) => `/publications/${pubId}`,
    userProfile: (uid) => `/users/${uid}`,
};
