import { StyleSheet } from 'react-native';
import { Spacing, Fonts } from '../../../constants/theme';

export const buildStyles = (theme) => StyleSheet.create({
    scrollContainer: {
        flexGrow: 1,
        backgroundColor: theme.background,
        marginTop: 5
    },
    header: {
        paddingHorizontal: Spacing.four,
        paddingTop: 70,
        paddingBottom: 8,
    },
    eyebrow: {
        fontSize: 13,
        fontWeight: '600',
        color: theme.secondary,
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginBottom: 6,
    },
    title: {
        fontSize: 26,
        fontWeight: 'bold',
        fontFamily: Fonts.sans,
        color: theme.text,
        lineHeight: 34,
    },
    body: {
        flex: 1,
        padding: Spacing.four,
        marginTop: -20,
    },
    step2Image: {
        width: '100%',
        height: 220,
        marginVertical: 16,
        borderRadius: 12,
        marginTop: -30,
        marginBottom: -2,
    },
    step3Image: {
        width: '100%',
        height: 100,
        marginVertical: 16,
        borderRadius: 12,
        marginTop: -15,
        marginBottom: 0,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: theme.text,
        marginBottom: 4,
    },
    sectionSubtitle: {
        fontSize: 14,
        color: '#888',
        marginBottom: 16,
    },
    input: {
        borderWidth: 1,
        borderColor: '#ccc',
        padding: 12,
        marginVertical: 8,
        borderRadius: 8,
        backgroundColor: '#fafafa',
        fontSize: 15,
    },
    strengthText: {
        fontSize: 13,
        fontWeight: '700',
        marginBottom: 10,
        marginLeft: 4,
    },
    switchContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginVertical: 12,
        paddingHorizontal: 4,
    },
    switchLabel: {
        fontSize: 15,
    },
    primaryButton: {
        backgroundColor: theme.primary,
        padding: 14,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 15,
    },
    buttonText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    divider: {
        textAlign: 'center',
        color: '#aaa',
        marginVertical: 18,
        fontSize: 12,
    },
    googleButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        paddingVertical: 14,
        borderRadius: 100,
        marginBottom: 5,
    },
    googleIconImage: {
        width: 22,
        height: 22,
        marginRight: 12,
    },
    googleButtonText: {
        color: '#1F2937',
        fontWeight: '600',
        fontSize: 16,
    },
    rowButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 10,
    },
    backButton: {
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: theme.primary,
        flex: 1,
    },
    flexButton: {
        flex: 1,
    },
    loginFooter: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 25,
        marginBottom: 15,
    },
    loginLink: {
        color: theme.primary,
        fontWeight: 'bold',
        fontSize: 15,
    },
    passwordContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 8,
        backgroundColor: '#fafafa',
        marginVertical: 8,
    },
    passwordInput: {
        flex: 1,
        padding: 12,
        fontSize: 15,
        color: theme.text,
    },
    eyeButton: {
        paddingHorizontal: 12,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'stretch',
    },
    dotsContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 8,
        paddingTop: 20,
        paddingBottom: 4,
    },
    dot: {
        height: 6,
        width: 40,
        borderRadius: 999,
    },
    dotActive: {
        backgroundColor: theme.tertiary,
    },
    dotInactive: {
        backgroundColor: theme.tertiaryInactive,
    },
});
